name: GachaKey
main: GachaKey\Main
version: 1.0
api: 4.0.0
author: Bluee-13
description: "GachaKey Shop"

commands:
  gachakey:
    description: "§ePremiums User"
    permission: gachakey.cmd

permissions:
  gachakey.cmd:
    description: "permissions"
    default: true
